@startuml Class diagram
!theme mono

class Game {
    - playerX: Player
    - playerO: Player
    - board: Board
    - current_round: int 

    + init_game(): None
    + play_game(): None
    + end_game(): None
}

class StringHolder {
    - welcomeStr: str 
    - ...
}

class Player {
    - team: str

    + make_move(board: Board): None
}

class AIPlayer {
    + make_move(board: Board): None
    + determine_move(board: Board): (int, int)
}

class Board {
    - board: list[str]

    + move_possible(): bool 
    + place_move(i: int, j: int): bool
    + game_over(): bool 
    + get_winner(): str
    + print_board(): None
}

Game o-- Board 
Game o-- Player
Game o-- StringHolder

Player <|-- AIPlayer

@enduml